# Generated by Django 3.1.7 on 2021-04-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ChannelV',
            field=models.URLField(default='https://docs.python.org/3/', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='PlaylistV',
            field=models.URLField(default='https://docs.python.org/3/', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='postdefault.jpg', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='linkV',
            field=models.URLField(default='https://docs.python.org/3/', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=600),
        ),
    ]
